// <auto-generated />
using System;
using Management.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Management.Migrations
{
    [DbContext(typeof(LABContext))]
    [Migration("20230517032234_V200")]
    partial class V200
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Management.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PrintOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("Name");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Management.Models.Connect", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double?>("BaudRate")
                        .HasColumnType("float");

                    b.Property<string>("Com")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComputerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("DataBit")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Parity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<bool>("Rts")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<double?>("StopBit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ComputerId", "PortId", "DeviceId")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL");

                    b.ToTable("Connect");
                });

            modelBuilder.Entity("Management.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodeBHYT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ProcessQc")
                        .HasColumnType("bit");

                    b.Property<string>("Protocol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Management.Models.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Management.Models.Function", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Name");

                    b.ToTable("Function");
                });

            modelBuilder.Entity("Management.Models.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Management.Models.Hospital", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("Management.Models.ImageCDHA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ResultCDHAId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ResultCDHAId");

                    b.ToTable("ImageCDHA");
                });

            modelBuilder.Entity("Management.Models.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Management.Models.Map", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("DeviceId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("FormatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TestCodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("TestcodeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TestcodeIn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestcodeIn3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestCodeId");

                    b.HasIndex("DeviceId", "TestCodeId", "TestcodeIn")
                        .IsUnique()
                        .HasFilter("[DeviceId] IS NOT NULL AND [TestCodeId] IS NOT NULL");

                    b.ToTable("Map");
                });

            modelBuilder.Entity("Management.Models.Object", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Object");
                });

            modelBuilder.Entity("Management.Models.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Age")
                        .HasColumnType("datetime2");

                    b.Property<string>("BenhAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("FullResultXN")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GetSampleTimeNS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GetSampleTimeSA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GetSampleTimeSAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GetSampleTimeXN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GetSampleTimeXQ")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsYear")
                        .HasColumnType("bit");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ObjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ProcessNS")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessSA")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessSAT")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessXN")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessXQ")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReturnResultTimeNS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnResultTimeSA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnResultTimeSAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnResultTimeXN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnResultTimeXQ")
                        .HasColumnType("datetime2");

                    b.Property<string>("Seq")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserInsertId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserProcessResultXQ")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserReturnResultNS")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserReturnResultSA")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserReturnResultSAT")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserReturnResultXN")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserReturnResultXQ")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserUpdateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ValidNS")
                        .HasColumnType("bit");

                    b.Property<bool>("ValidSA")
                        .HasColumnType("bit");

                    b.Property<bool>("ValidSAT")
                        .HasColumnType("bit");

                    b.Property<bool>("ValidXN")
                        .HasColumnType("bit");

                    b.Property<bool>("ValidXQ")
                        .HasColumnType("bit");

                    b.Property<bool>("WaitNS")
                        .HasColumnType("bit");

                    b.Property<bool>("WaitSA")
                        .HasColumnType("bit");

                    b.Property<bool>("WaitSAT")
                        .HasColumnType("bit");

                    b.Property<bool>("WaitXN")
                        .HasColumnType("bit");

                    b.Property<bool>("WaitXQ")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("Sid")
                        .IsUnique()
                        .HasFilter("[Sid] IS NOT NULL");

                    b.HasIndex("UserInsertId");

                    b.HasIndex("UserProcessResultXQ");

                    b.HasIndex("UserReturnResultNS");

                    b.HasIndex("UserReturnResultSA");

                    b.HasIndex("UserReturnResultSAT");

                    b.HasIndex("UserReturnResultXN");

                    b.HasIndex("UserReturnResultXQ");

                    b.HasIndex("UserUpdateId");

                    b.HasIndex("Seq", "PatientId", "PatientName", "InsertTime");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Management.Models.PrintSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("PrintSample");
                });

            modelBuilder.Entity("Management.Models.ResultCDHA", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceCodeBHYT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyResultForHis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PushBHYT")
                        .HasColumnType("bit");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("SieuAmTim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suggest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserInsertId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserUpdateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserInsertId");

                    b.HasIndex("UserUpdateId");

                    b.HasIndex("InsertTime", "PatientId", "ServiceId");

                    b.ToTable("ResultCDHA");
                });

            modelBuilder.Entity("Management.Models.ResultStandard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ComputerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosNeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Result")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Seq")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("TestCodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("TestCodeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCodeIn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCodeIn3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TestCodeId");

                    b.HasIndex("Seq", "TestCodeId", "Status");

                    b.ToTable("ResultStandard");
                });

            modelBuilder.Entity("Management.Models.ResultXN", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceCodeBHYT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyResultForHis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("PosNeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PushBHYT")
                        .HasColumnType("bit");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StatusResult")
                        .HasColumnType("int");

                    b.Property<long?>("TestCodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("TicketItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserInsertId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserUpdateId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ValidPrint")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValidTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TestCodeId");

                    b.HasIndex("UserInsertId");

                    b.HasIndex("UserUpdateId");

                    b.HasIndex("PatientId", "TestCodeId", "InsertTime", "ValidTime");

                    b.ToTable("ResultXN");
                });

            modelBuilder.Entity("Management.Models.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CategorieId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suggest")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Sample");
                });

            modelBuilder.Entity("Management.Models.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PrintOrder")
                        .HasColumnType("int");

                    b.Property<long?>("PrintSampleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ProcessType")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("PrintSampleId");

                    b.HasIndex("CategoryId", "PrintSampleId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Management.Models.ServiceTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TestCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestCodeId");

                    b.HasIndex("ServiceId", "TestCodeId")
                        .IsUnique()
                        .HasFilter("[ServiceId] IS NOT NULL AND [TestCodeId] IS NOT NULL");

                    b.ToTable("ServiceTest");
                });

            modelBuilder.Entity("Management.Models.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("ComputerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsConnect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManage")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ComputerId", "IsConnect", "IsManage")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Management.Models.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("Management.Models.TestCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodeBHYT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HigherLimit")
                        .HasColumnType("float");

                    b.Property<bool>("IsTestChild")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTestHead")
                        .HasColumnType("bit");

                    b.Property<double?>("LowerLimit")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameBHYT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalRangeF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalRangeM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrintOrder")
                        .HasColumnType("int");

                    b.Property<long?>("TestTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TestTypeId");

                    b.HasIndex("Name", "CategoryId");

                    b.ToTable("TestCode");
                });

            modelBuilder.Entity("Management.Models.TestType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("TestType");
                });

            modelBuilder.Entity("Management.Models.Type", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Management.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Name");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Management.Models.UserFunction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("FunctionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("UserId", "FunctionId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [FunctionId] IS NOT NULL");

                    b.ToTable("UserFunction");
                });

            modelBuilder.Entity("Management.Models.UserType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId", "TypeId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [TypeId] IS NOT NULL");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("Management.Models.WorkOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCodeIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCodeIn2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserInsertId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserInsertId");

                    b.HasIndex("PatientId", "InsertTime", "Status");

                    b.ToTable("WorkOrder");
                });

            modelBuilder.Entity("Management.Models.Category", b =>
                {
                    b.HasOne("Management.Models.Group", "Group")
                        .WithMany("Categories")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Management.Models.Connect", b =>
                {
                    b.HasOne("Management.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Management.Models.ImageCDHA", b =>
                {
                    b.HasOne("Management.Models.ResultCDHA", "ResultCDHA")
                        .WithMany("ImageCDHAs")
                        .HasForeignKey("ResultCDHAId");

                    b.Navigation("ResultCDHA");
                });

            modelBuilder.Entity("Management.Models.Map", b =>
                {
                    b.HasOne("Management.Models.Device", "Device")
                        .WithMany("Maps")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Management.Models.TestCode", "TestCode")
                        .WithMany("Maps")
                        .HasForeignKey("TestCodeId");

                    b.Navigation("Device");

                    b.Navigation("TestCode");
                });

            modelBuilder.Entity("Management.Models.Patient", b =>
                {
                    b.HasOne("Management.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("Management.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Management.Models.Object", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId");

                    b.HasOne("Management.Models.User", "UserInsert")
                        .WithMany()
                        .HasForeignKey("UserInsertId");

                    b.HasOne("Management.Models.User", "UserProcessXQ")
                        .WithMany()
                        .HasForeignKey("UserProcessResultXQ");

                    b.HasOne("Management.Models.User", "UserNS")
                        .WithMany()
                        .HasForeignKey("UserReturnResultNS");

                    b.HasOne("Management.Models.User", "UserSA")
                        .WithMany()
                        .HasForeignKey("UserReturnResultSA");

                    b.HasOne("Management.Models.User", "UserSAT")
                        .WithMany()
                        .HasForeignKey("UserReturnResultSAT");

                    b.HasOne("Management.Models.User", "UserXN")
                        .WithMany()
                        .HasForeignKey("UserReturnResultXN");

                    b.HasOne("Management.Models.User", "UserReturnXQ")
                        .WithMany()
                        .HasForeignKey("UserReturnResultXQ");

                    b.HasOne("Management.Models.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UserUpdateId");

                    b.Navigation("Doctor");

                    b.Navigation("Location");

                    b.Navigation("Object");

                    b.Navigation("UserInsert");

                    b.Navigation("UserNS");

                    b.Navigation("UserProcessXQ");

                    b.Navigation("UserReturnXQ");

                    b.Navigation("UserSA");

                    b.Navigation("UserSAT");

                    b.Navigation("UserUpdate");

                    b.Navigation("UserXN");
                });

            modelBuilder.Entity("Management.Models.ResultCDHA", b =>
                {
                    b.HasOne("Management.Models.Doctor", "Doctor")
                        .WithMany("ResultCDHAs")
                        .HasForeignKey("DoctorId");

                    b.HasOne("Management.Models.Patient", "Patient")
                        .WithMany("ResultCDHAs")
                        .HasForeignKey("PatientId");

                    b.HasOne("Management.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("Management.Models.User", "UserInsert")
                        .WithMany()
                        .HasForeignKey("UserInsertId");

                    b.HasOne("Management.Models.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UserUpdateId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("UserInsert");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("Management.Models.ResultStandard", b =>
                {
                    b.HasOne("Management.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("Management.Models.TestCode", "TestCode")
                        .WithMany()
                        .HasForeignKey("TestCodeId");

                    b.Navigation("Device");

                    b.Navigation("TestCode");
                });

            modelBuilder.Entity("Management.Models.ResultXN", b =>
                {
                    b.HasOne("Management.Models.Doctor", "Doctor")
                        .WithMany("ResultXNs")
                        .HasForeignKey("DoctorId");

                    b.HasOne("Management.Models.Patient", "Patient")
                        .WithMany("ResultXNs")
                        .HasForeignKey("PatientId");

                    b.HasOne("Management.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("Management.Models.TestCode", "TestCode")
                        .WithMany()
                        .HasForeignKey("TestCodeId");

                    b.HasOne("Management.Models.User", "UserInsert")
                        .WithMany()
                        .HasForeignKey("UserInsertId");

                    b.HasOne("Management.Models.User", "UserUpdate")
                        .WithMany()
                        .HasForeignKey("UserUpdateId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Service");

                    b.Navigation("TestCode");

                    b.Navigation("UserInsert");

                    b.Navigation("UserUpdate");
                });

            modelBuilder.Entity("Management.Models.Sample", b =>
                {
                    b.HasOne("Management.Models.Category", "Category")
                        .WithMany("Samples")
                        .HasForeignKey("CategorieId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Management.Models.Service", b =>
                {
                    b.HasOne("Management.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Management.Models.PrintSample", "PrintSample")
                        .WithMany("Services")
                        .HasForeignKey("PrintSampleId");

                    b.Navigation("Category");

                    b.Navigation("PrintSample");
                });

            modelBuilder.Entity("Management.Models.ServiceTest", b =>
                {
                    b.HasOne("Management.Models.Service", "Service")
                        .WithMany("ServiceTests")
                        .HasForeignKey("ServiceId");

                    b.HasOne("Management.Models.TestCode", "TestCode")
                        .WithMany()
                        .HasForeignKey("TestCodeId");

                    b.Navigation("Service");

                    b.Navigation("TestCode");
                });

            modelBuilder.Entity("Management.Models.Session", b =>
                {
                    b.HasOne("Management.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Management.Models.TestCode", b =>
                {
                    b.HasOne("Management.Models.Category", "Category")
                        .WithMany("TestCodes")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Management.Models.TestType", "TestType")
                        .WithMany("TestCodes")
                        .HasForeignKey("TestTypeId");

                    b.Navigation("Category");

                    b.Navigation("TestType");
                });

            modelBuilder.Entity("Management.Models.UserFunction", b =>
                {
                    b.HasOne("Management.Models.Function", "Function")
                        .WithMany("UserFunctions")
                        .HasForeignKey("FunctionId");

                    b.HasOne("Management.Models.User", "User")
                        .WithMany("UserFunctions")
                        .HasForeignKey("UserId");

                    b.Navigation("Function");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Management.Models.UserType", b =>
                {
                    b.HasOne("Management.Models.Type", "Type")
                        .WithMany("UserTypes")
                        .HasForeignKey("TypeId");

                    b.HasOne("Management.Models.User", "User")
                        .WithMany("UserTypes")
                        .HasForeignKey("UserId");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Management.Models.WorkOrder", b =>
                {
                    b.HasOne("Management.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("Management.Models.Patient", "Patient")
                        .WithMany("WorkOrders")
                        .HasForeignKey("PatientId");

                    b.HasOne("Management.Models.User", "UserInsert")
                        .WithMany()
                        .HasForeignKey("UserInsertId");

                    b.Navigation("Device");

                    b.Navigation("Patient");

                    b.Navigation("UserInsert");
                });

            modelBuilder.Entity("Management.Models.Category", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("Services");

                    b.Navigation("TestCodes");
                });

            modelBuilder.Entity("Management.Models.Device", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("Management.Models.Doctor", b =>
                {
                    b.Navigation("ResultCDHAs");

                    b.Navigation("ResultXNs");
                });

            modelBuilder.Entity("Management.Models.Function", b =>
                {
                    b.Navigation("UserFunctions");
                });

            modelBuilder.Entity("Management.Models.Group", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Management.Models.Patient", b =>
                {
                    b.Navigation("ResultCDHAs");

                    b.Navigation("ResultXNs");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("Management.Models.PrintSample", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Management.Models.ResultCDHA", b =>
                {
                    b.Navigation("ImageCDHAs");
                });

            modelBuilder.Entity("Management.Models.Service", b =>
                {
                    b.Navigation("ServiceTests");
                });

            modelBuilder.Entity("Management.Models.TestCode", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("Management.Models.TestType", b =>
                {
                    b.Navigation("TestCodes");
                });

            modelBuilder.Entity("Management.Models.Type", b =>
                {
                    b.Navigation("UserTypes");
                });

            modelBuilder.Entity("Management.Models.User", b =>
                {
                    b.Navigation("UserFunctions");

                    b.Navigation("UserTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
